spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.2.102:8081 # Sentinel Dashboard 地址，比如你启动了 Sentinel 控制台在 8080 端口
        port: 8730               # Sentinel 客户端与服务端通信端口，默认 8719，若被占用会自动递增
#        client-ip: 192.168.3.2
      eager: true                # 是否启动时立即初始化 Sentinel，默认 false
      filter:
        enabled: true            # 开启 Sentinel 对 Web 请求的拦截，默认 true